# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import peer_pb2 as peer__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in peer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PeerTransportStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/PeerTransport/Ping',
                request_serializer=peer__pb2.PingRequest.SerializeToString,
                response_deserializer=peer__pb2.PingReply.FromString,
                _registered_method=True)
        self.GetManifest = channel.unary_unary(
                '/PeerTransport/GetManifest',
                request_serializer=peer__pb2.ManifestRequest.SerializeToString,
                response_deserializer=peer__pb2.ManifestReply.FromString,
                _registered_method=True)
        self.ListLocalShards = channel.unary_unary(
                '/PeerTransport/ListLocalShards',
                request_serializer=peer__pb2.LocalShardsRequest.SerializeToString,
                response_deserializer=peer__pb2.LocalShardsReply.FromString,
                _registered_method=True)
        self.PullShard = channel.unary_stream(
                '/PeerTransport/PullShard',
                request_serializer=peer__pb2.PullShardRequest.SerializeToString,
                response_deserializer=peer__pb2.ShardChunk.FromString,
                _registered_method=True)
        self.ReportThroughput = channel.unary_unary(
                '/PeerTransport/ReportThroughput',
                request_serializer=peer__pb2.ThroughputReport.SerializeToString,
                response_deserializer=peer__pb2.ReportThroughputReply.FromString,
                _registered_method=True)
        self.GetLeasePlan = channel.unary_unary(
                '/PeerTransport/GetLeasePlan',
                request_serializer=peer__pb2.LeasePlanRequest.SerializeToString,
                response_deserializer=peer__pb2.LeasePlanReply.FromString,
                _registered_method=True)
        self.ReportRunCompletion = channel.unary_unary(
                '/PeerTransport/ReportRunCompletion',
                request_serializer=peer__pb2.RunCompletion.SerializeToString,
                response_deserializer=peer__pb2.ReportRunCompletionReply.FromString,
                _registered_method=True)
        self.GetRunCompletions = channel.unary_unary(
                '/PeerTransport/GetRunCompletions',
                request_serializer=peer__pb2.RunCompletionsRequest.SerializeToString,
                response_deserializer=peer__pb2.RunCompletionsReply.FromString,
                _registered_method=True)
        self.PushPayload = channel.stream_unary(
                '/PeerTransport/PushPayload',
                request_serializer=peer__pb2.PayloadMessage.SerializeToString,
                response_deserializer=peer__pb2.PushPayloadReply.FromString,
                _registered_method=True)
        self.GetPeerState = channel.unary_unary(
                '/PeerTransport/GetPeerState',
                request_serializer=peer__pb2.PeerStateRequest.SerializeToString,
                response_deserializer=peer__pb2.PeerStateReply.FromString,
                _registered_method=True)


class PeerTransportServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetManifest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLocalShards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportThroughput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLeasePlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportRunCompletion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunCompletions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushPayload(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeerState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeerTransportServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=peer__pb2.PingRequest.FromString,
                    response_serializer=peer__pb2.PingReply.SerializeToString,
            ),
            'GetManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetManifest,
                    request_deserializer=peer__pb2.ManifestRequest.FromString,
                    response_serializer=peer__pb2.ManifestReply.SerializeToString,
            ),
            'ListLocalShards': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLocalShards,
                    request_deserializer=peer__pb2.LocalShardsRequest.FromString,
                    response_serializer=peer__pb2.LocalShardsReply.SerializeToString,
            ),
            'PullShard': grpc.unary_stream_rpc_method_handler(
                    servicer.PullShard,
                    request_deserializer=peer__pb2.PullShardRequest.FromString,
                    response_serializer=peer__pb2.ShardChunk.SerializeToString,
            ),
            'ReportThroughput': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportThroughput,
                    request_deserializer=peer__pb2.ThroughputReport.FromString,
                    response_serializer=peer__pb2.ReportThroughputReply.SerializeToString,
            ),
            'GetLeasePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLeasePlan,
                    request_deserializer=peer__pb2.LeasePlanRequest.FromString,
                    response_serializer=peer__pb2.LeasePlanReply.SerializeToString,
            ),
            'ReportRunCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportRunCompletion,
                    request_deserializer=peer__pb2.RunCompletion.FromString,
                    response_serializer=peer__pb2.ReportRunCompletionReply.SerializeToString,
            ),
            'GetRunCompletions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunCompletions,
                    request_deserializer=peer__pb2.RunCompletionsRequest.FromString,
                    response_serializer=peer__pb2.RunCompletionsReply.SerializeToString,
            ),
            'PushPayload': grpc.stream_unary_rpc_method_handler(
                    servicer.PushPayload,
                    request_deserializer=peer__pb2.PayloadMessage.FromString,
                    response_serializer=peer__pb2.PushPayloadReply.SerializeToString,
            ),
            'GetPeerState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeerState,
                    request_deserializer=peer__pb2.PeerStateRequest.FromString,
                    response_serializer=peer__pb2.PeerStateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PeerTransport', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PeerTransport', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PeerTransport(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PeerTransport/Ping',
            peer__pb2.PingRequest.SerializeToString,
            peer__pb2.PingReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PeerTransport/GetManifest',
            peer__pb2.ManifestRequest.SerializeToString,
            peer__pb2.ManifestReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLocalShards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PeerTransport/ListLocalShards',
            peer__pb2.LocalShardsRequest.SerializeToString,
            peer__pb2.LocalShardsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/PeerTransport/PullShard',
            peer__pb2.PullShardRequest.SerializeToString,
            peer__pb2.ShardChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportThroughput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PeerTransport/ReportThroughput',
            peer__pb2.ThroughputReport.SerializeToString,
            peer__pb2.ReportThroughputReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLeasePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PeerTransport/GetLeasePlan',
            peer__pb2.LeasePlanRequest.SerializeToString,
            peer__pb2.LeasePlanReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportRunCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PeerTransport/ReportRunCompletion',
            peer__pb2.RunCompletion.SerializeToString,
            peer__pb2.ReportRunCompletionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunCompletions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PeerTransport/GetRunCompletions',
            peer__pb2.RunCompletionsRequest.SerializeToString,
            peer__pb2.RunCompletionsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushPayload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/PeerTransport/PushPayload',
            peer__pb2.PayloadMessage.SerializeToString,
            peer__pb2.PushPayloadReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeerState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PeerTransport/GetPeerState',
            peer__pb2.PeerStateRequest.SerializeToString,
            peer__pb2.PeerStateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
